#!/bin/bash

echo "Starting Sauce Connect"
if [ ! -x ./sc-4.3.11-*/bin/sc ]; then
  wget http://saucelabs.com/downloads/sc-4.3.11-linux.tar.gz
  tar -zxvf sc-4.3.11-linux.tar.gz
fi
READY_FILE=sauce-connect-ready$RANDOM
./sc-4.3.11-*/bin/sc -i $TRAVIS_JOB_NUMBER -f $READY_FILE -l sauce-connect.log -B all -t localhost &
echo "Waiting for Connect to be ready before exiting"
while [ ! -f $READY_FILE ]; do
  sleep .5
done
