#!/bin/bash
#
# Installs Chrome or Firefox if missing
#
BINDIR=./browsers/bin

if [ -z $BROWSER ]; then
	echo "No BROWSER variable specified, defaulting to locally installed Chrome"
	# Default to Chrome
  BROWSER="chrome"
	case $OSTYPE in
		darwin*) BROWSERBIN="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";;
		linux*) ;;
	esac
else
	BROWSERBIN=$BINDIR/$BROWSER-$BVER
fi

if [ $BROWSER == 'ie' ]; then
  protractor tests/protractor-saucelabs-ie.conf.js
else
  if [ ! -x $BROWSERBIN ]; then
    echo "Installing browser."
    ./node_modules/travis-multirunner/setup.sh
  fi
  PATH=$PATH:./node_modules/.bin
  # Karma uses ${BROWSER}_BIN, eg. CHROME_BIN, to override the path to the browser
  BROWSER_UPPER=$(echo "$BROWSER" | tr '[:lower:]' '[:upper:]')
  BROWSER_CAMEL=${BROWSER_UPPER:0:1}${BROWSER:1}
  export ${BROWSER_UPPER}_BIN="$BROWSERBIN"
  echo "Starting Karma for browser $BROWSER_CAMEL"
  karma start tests/karma.conf.js --single-run --browsers $BROWSER_CAMEL

  echo "Running Protractor tests on Browserstack"
  wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  unzip BrowserStackLocal-linux-x64.zip
  ./BrowserStackLocal $BROWSERSTACK_KEY localhost,8001,0 > /dev/null &
  sleep 10
  protractor tests/protractor-browserstack-$BROWSER.conf.js
fi
