#!/bin/bash

echo "Starting BrowserStackLocal"
if [ ! -x ./BrowserStackLocal ]; then
  wget http://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  unzip BrowserStackLocal-linux-x64.zip
fi
./BrowserStackLocal $BROWSERSTACK_KEY localhost,8001,0 > /dev/null &
echo $! > ./tests/scripts/browserstack-local-$TRAVIS_JOB_NUMBER.pid
sleep 10
